### ISSUE TITLE
Support automatic migration depending on module ref vs module state ref

### ISSUE THREAD

**Issue by nitrocode** [minamijoyo/tfmigrate#19] opened 2021-04-01 15:23 UTC
Great tool by the way.

Please let me know if this is feasible.

## Context

Previously applied module code which creates `module.s3.aws_s3_bucket.that` resource.

```hcl
module "s3" {
  source = "some-module-source?ref=tags/0.1.0"
```

Now the source has been bumped to `0.2.0` which changes the name `that` to `this`

The new version contains a directory `migrate/0.1.0_to_0.2.0.hcl` file which can be downloaded and run via `tfmigrate`

## Proposal

User updates the source to a new version of a module

```bash
terraform init -upgrade
terraform plan
```

User notices creations and destroys of similar resources

Running this or similar

```bash
tfmigrate plan --auto-detect
tfmigrate plan --target module.s3
tfmigrate plan
tfmigrate apply
```

1. Detect previously applied module versions
1. Detect if new module version will be applied
1. Check for a standardized module migration directory `migrate/` which contains the previous version and new version like `x.y.z_to_a.b.c.hcl`
    * could also use multiple directories to autodetect like `tfmigrate`, `tfupgrade`, `upgrade`, etc
1. if `plan`, do not prompt user
1. if `apply`, prompt user to migrate

**Comment by minamijoyo** [comment] 2021-04-07 05:06
Interesting. It's a good idea that a module author provides how to migrate an old state.

I think there are some problems:

- The module author doesn't know actual resource address and can provide only a migration template file which cannot directly be applied by the module user.
- The tfmigrate was designed to be suitable for GitOps, so fully automatic will be unclear what happens and cannot confirm by the module user and other reviewers. I prefer more declarative way that the module user to generate a migration file from the template.
- Previously applied version is not recorded in the state. It can only be detected from source code differences. It's not impossible, but it will be hard to implement.
- Ideally, the migration file should be generated at the same time as editing the terraform configuration file, which knows the full context, but there are many issues to be solved in implementation.
- If previously applied version is an outdated patch version and the module has multiple migration templates, which file to be applied can be detected by the semantic versioning. It's also not impossible, but it needs many rules to work correctly.
- If we support the automatic migration, then the module user probably expects to resolve all diffs with no changes, but it's a wrong expectation. Not all breaking changes for the module can be migrated with state operations., for example, adding a new resource or attribute. This leads a bad UX. The module author should clarify when and how to migrate state in the CHANGELOG or README.

By the way, I guess we may be able to generate a migration file only from a tfplan file with some heuristics in a simple case such as renaming a resource in module. If we go forward this direction, we can use it for wider range of cases, not only module upgrade, but also fixing state drifts caused by changing resource outside of Terraform. Of course, it's not perfect, it's best-effort feature, but at least the module user probably doesn't expect everything will be fixed magically.

**Comment by barryib** [comment] 2021-05-31 22:18
I think it'll be better to let module developers to generate migration file from template. That was my first thought for [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1101). But after I started, I noticed that I had a lot of code duplication.

From that, I was wondering if we can add annotation like in ORM Schema Migration directly in code. Something like this (thinking loud):

```hcl
#tfmigrate:mv:aws_autoscaling_group.foo:your-comment
resource "aws_autoscaling_group" "workers_launch_template" {
  count = var.create_eks ? local.worker_group_launch_template_count : 0
  name_prefix = join(
    "-",
    compact(
      [
        coalescelist(aws_eks_cluster.this[*].name, [""])[0],
        lookup(var.worker_groups_launch_template[count.index], "name", count.index)
      ]
    )
  )
}
```

Where `aws_autoscaling_group.foo` was the old name.

With that, we can:
- `tfmigrate generate` to generate migration file from config and state
- `tfmigrate plan`
- `tfmigrate apply`

In all cases, this is a really wanted feature for all module developers.

**Comment by minamijoyo** [comment] 2021-06-02 00:43
@barryib Thank you for your idea!

Aside from the difficulty of implementing parsing comments, I think it would probably work for a simple case, but if a resource in a parent module will be moved into a submodule and a root module has two instances of the parent module, how can we know their old address to generate a migration file? The tfmigrate doesn't have a context how to map two old addresses to new ones.

**Comment by nitrocode** [comment] 2021-06-22 15:18
> if a resource in a parent module will be moved into a submodule and a root module has two instances of the parent module, how can we know their old address to generate a migration file? The tfmigrate doesn't have a context how to map two old addresses to new ones.

Perhaps the `tfmigrate generate` can be semiautomated

```shell
$ tfmigrate generate <module-name> <version-old> <version-new>

initializing modules...
analyzing resources of <module-name> <version-old>...
analyzing resources of <module-name> <version-new>...
analyzing differences....

Found 5 differences

#1: module.<name>.security_group exists in <version-old> but not in <version-new>
#1: module.<name>.module.security_group is new
#1: module.<name>.module.security_group.security_group is new
#1: is deleted module.<name>.security_group the same as module.security_group.security_group ? [Ny]  y

#2: #...

...

Generated `tfmigrate_<module-name>_<version-old>_<version-new>.hcl!
```

**Comment by minamijoyo** [comment] 2021-07-21 07:59
FYI: I noticed that the Terraform core team seems to be working on a native support for "moved" block. Looks promising.
https://github.com/hashicorp/terraform/pull/29126

**Comment by apparentlymart** [comment] 2021-07-22 21:06
Hello! Thanks for linking over to that docs PR I was working on, because I hadn't previously noticed this discussion over here!

From what I understood of the discussion above it does seem like we're aiming at a similar set of use-cases as what this issue is discussing. Our development work on this is still pretty early and we don't have a functioning implementation in the main branch yet, but if anyone here would be interested we'd love to have some folks try out the functionality in an alpha build and let us know how it works out for some real-world modules. We're certainly not trying to solve every possible problem in the first release, because of course then we'd likely never actually ship it, but our initial area of focus _is_ on this idea of renaming objects (resources/modules) or moving them into and out of modules and so I expect you all will have some interesting real examples to try it out against!

Once we have things ready for feedback in at least one alpha release someone on our team will post a note over in [our community forum](https://discuss.hashicorp.com/c/terraform-core/27) about it, though I'll do my best to remember to come back and note it here too.

**Comment by minamijoyo** [comment] 2021-12-16 03:04
@nitrocode Can we close this issue by a new `moved` block introduced in Terraform v1.1?
https://www.hashicorp.com/blog/terraform-1-1-improves-refactoring-and-the-cloud-cli-experience

**Closed** 2021-12-17 06:57 UTC
